const teams = [
    {
        name: "Chennai Super Kings",
        owner: "Chennai Super Kings Cricket ltd.",
        coach :"Stephen Fleming",
        venue: "M. A. Chidambaram Stadium",
        captain: "MS Dhoni",
        winners: "2010, 2011, 2018",
        teamId: "csk"
    },
    {
        name: " Delhi Capitals",
        owner: "GMR Sports Pvt .Ltd & JSW Sports Pvt Ltd",
        coach: "Ricky Ponting",
        venue: "Feroz Shah Kotla Ground",
        captain: "Shreyas Iyer",
        winners: "",
        teamId: "dc"
    },
    {
        name: "Kings XI Punjab",
        owner: "KPH Dream Cricket Private Limited",
        coach: "Anil Kumble",
        venue: "IS Bindra Stadium",
        captain: "K L Rahul",
        winners: "",
        teamId: "kxip"
    },
    {
        name: "Kolkata Knight Riders",
        winners: "2012, 2014",
        owner: "Knight Riders Sports Private Ltd",
        coach: "Brendon McCullum",
        venue: "Eden Gardens",
        captain: "Eoin Morgan",
        teamId: "kkr"
    },
    {
        name: "Mumbai Indians",
        winners: "2013, 2015, 2017, 2019,2020",
        owner: "Indiawin Sports Pvt. Ltd",
        coach: "Mahela Jayawardene",
        venue: "Wankhede Stadium",
        captain: "Rohit Sharma",
        teamId: "mi"
    },
    {
        name: "Rajasthan Royals",
        winners: "2008",
        owner: "Royal Multisport Pvt. Ltd",
        coach: "Andrew McDonald",
        venue: "Sawai Mansingh Stadium",
        captain: "Steve Smith",
        teamId: "rr"
    },
    {
        name: "Royal Challengers Bangalore",
        owner: "Royal Challengers Sports Private Ltd",
        coach: "Simon Katich",
        venue: "M. Chinnaswamy Stadium",
        captain: "Virat Kohli",
        winners: "",
        teamId: "rcb"
    },
    {
        name: "Sunrisers Hyderabad",
        winners: "2016",
        owner: "SUN TV Network",
        coach: "Trevor Bayliss",
        venue: "Rajiv Gandhi Intl. Cricket Stadium",
        captain: "David Warner",
        teamId: "srh"
    }
];


  

const players = [
    { 
        team: "csk",
        name: "MS Dhoni",
        isCaptain: true,
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/0.png",
        stats: '  14 Matches   200 Runs   0 Wickets  ' 
    },
    {
        name: "Imran Tahir",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/1.png",
        stats: '  3 Matches   13 Runs   1 Wickets  ' },
    {
        name: "Lungi Ngidi",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/2.png",
        stats: '  4 Matches   0 Runs   9 Wickets  ' },
    {
        name: "Ruturaj Gaikwad",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/3.png",
        stats: '  6 Matches   204 Runs   0 Wickets  ' },
    {
        name: "Shane Watson",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/4.png",
        stats: '  11 Matches   299 Runs   0 Wickets  ' },
    {
        name: "Ambati Rayudu",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/5.png",
        stats: '  12 Matches   359 Runs   0 Wickets  ' },
    {
        name: "Murali Vijay",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/6.png",
        stats: '  3 Matches   32 Runs   0 Wickets  ' },
    {
        name: "Kedar Jadhav",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/7.png",
        stats: '  8 Matches   62 Runs   0 Wickets  ' },
    {
        name: "Ravindra Jadeja",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/8.png",
        stats: '  14 Matches   232 Runs   6 Wickets  ' },
    {
        name: "Deepak Chahar",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/9.png",
        stats: '  14 Matches   7 Runs   12 Wickets  ' },
    {
        name: "Piyush Chawla",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/10.png",
        stats: '  7 Matches   0 Runs   6 Wickets  ' },
    {
        name: "Narayan Jagadeesan",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/11.png",
        stats: '  5 Matches   33 Runs   0 Wickets  ' },
    {
        name: "Mitchell Santner",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/12.png",
        stats: '  2 Matches   0 Runs   2 Wickets  ' },
    {
        name: "KM Asif",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/13.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: "Shardul Thakur",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/14.png",
        stats: '  9 Matches   12 Runs   10 Wickets  ' },
    {
        name: "R Sai Kisho",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/15.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: "Faf du Pless",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/16.png",
        stats: '  13 Matches   449 Runs   0 Wickets  ' },
    {
        name: "Monu Kumar",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/17.png",
        stats: '  1 Matches   0 Runs   0 Wickets  ' },
    {
        name: "Dwayne Bravo",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/18.png",
        stats: '  6 Matches   7 Runs   6 Wickets  ' },
    {
        name: "Josh Hazlewood",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/19.png",
        stats: '  3 Matches   0 Runs   1 Wickets  ' },
    {
        name: "Sam Curran",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/20.png",
        stats: '  14 Matches   186 Runs   13 Wickets  ' },
    {
        name: "Karn Sharma",
        isCaptain: false,
        team: "csk",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/csk/21.png",
        stats: '  5 Matches   0 Runs   5 Wickets  ' },

      { 
          name: "Shreyas Iyer ",
          isCaptain: true,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/0.png",
          stats: '  17 Matches   519 Runs   0 Wickets  ' },
      { 
          name: "Kagiso Rabada",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/1.png",
          stats: '  17 Matches   56 Runs   30 Wickets  ' },
      { 
          name: "Marcus Stoinis",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/2.png",
          stats: '  17 Matches   352 Runs   13 Wickets  ' },
      { 
          name: "Sandeep Lamichhane",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/3.png",
          stats: '  0 Matches   0 Runs   0 Wickets  ' },
      { 
          name: "Ishant Sharma",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/4.png",
          stats: '  1 Matches   0 Runs   0 Wickets  ' },
      { 
          name: "Ajinkya Rahane",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/5.png",
          stats: '  9 Matches   113 Runs   0 Wickets  ' },
      { 
          name: "Ravichandran Ashwin",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/6.png",
          stats: '  15 Matches   37 Runs   13 Wickets  ' },
      { 
          name: "Shikhar Dhawan",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/7.png",
          stats: '  17 Matches   618 Runs   0 Wickets  ' },
      { 
          name: "Shimron Hetmyer",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/8.png",
          stats: '  12 Matches   185 Runs   0 Wickets  ' },
      { 
          name: "Daniel Sams",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/9.png",
          stats: '  3 Matches   0 Runs   0 Wickets  ' },
      { 
          name: "Alex Carey",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/10.png",
          stats: '  3 Matches   32 Runs   0 Wickets  ' },
      { 
          name: "Mohit Sharma",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/11.png",
          stats: '  1 Matches   0 Runs   1 Wickets  ' },
      { 
          name: "Prithvi Shaw",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/12.png",
          stats: '  13 Matches   228 Runs   0 Wickets  ' },
      { 
          name: "Pravin Dubey",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/13.png",
          stats: '  3 Matches   7 Runs   0 Wickets  ' },
      { 
          name: "Lalith Yadav",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/14.png",
          stats: '  0 Matches   0 Runs   0 Wickets  ' },
      { 
          name: "Avesh Khan",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/15.png",
          stats: '  1 Matches   0 Runs   0 Wickets  ' },
      { 
          name: "Axar Patel",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/16.png",
          stats: '  15 Matches   117 Runs   9 Wickets  ' },
      { 
          name: "Tushar Deshpande",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/17.png",
          stats: '  5 Matches   21 Runs   3 Wickets  ' },
      { 
          name: "Anrich Nortje",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/18.png",
          stats: '  16 Matches   7 Runs   22 Wickets  ' },
      { 
          name: "Rishabh Pant",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/19.png",
          stats: '  14 Matches   343 Runs   0 Wickets  ' },
      { 
          name: "Harshal Patel",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/20.png",
          stats: '  5 Matches   21 Runs   3 Wickets  ' },
      { 
          name: "Keemo Paul",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/21.png",
          stats: '  0 Matches   0 Runs   0 Wickets  ' },
      { 
          name: "Amit Mishra",
          isCaptain: false,
          team: "dc",
          url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/dc/22.png",
          stats: '  3 Matches   0 Runs   3 Wickets  ' },

  { name: "KL Rahul",
  isCaptain: true,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/0.png",
    stats: '  14 Matches   670 Runs   0 Wickets  ' 
    },
  { name: "Harpreet Brar",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/1.png",
    stats: '  1 Matches   0 Runs   0 Wickets  ' 
    },
  { name: "Ishan Porel",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/2.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' 
    },
  { name: "Mandeep Singh",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/3.png",
    stats: '  7 Matches   130 Runs   0 Wickets  ' 
    },
  { name: "Jimmy Neesham",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/4.png",
    stats: '  5 Matches   19 Runs   2 Wickets  ' 
    },
  { name: "Tajinder Singh",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/5.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' 
    },
  { name: "Chris Jordan",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/6.png",
    stats: '  9 Matches   29 Runs   9 Wickets  ' 
    },
  { name: "Karun Nair",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/7.png",
    stats: '  4 Matches   16 Runs   0 Wickets  ' 
    },
  { name: "Deepak Hooda",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/8.png",
    stats: '  7 Matches   101 Runs   0 Wickets  ' 
    },
  { name: "Ravi Bishnoi",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/9.png",
    stats: '  14 Matches   7 Runs   12 Wickets  ' 
    },
  { name: "Arshdeep Singh",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/10.png",
    stats: '  8 Matches   0 Runs   9 Wickets  ' 
    },
  { name: "Glenn Maxwell",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/11.png",
    stats: '  13 Matches   108 Runs   3 Wickets  ' 
    },
  { name: "Mujeeb Ur Rahman",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/12.png",
    stats: '  2 Matches   1 Runs   0 Wickets  ' 
    },
  { name: "Sarfaraz Khan",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/13.png",
    stats: '  5 Matches   33 Runs   0 Wickets  ' 
    },
  { name: "Sheldon Cottrell",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/14.png",
    stats: '  6 Matches   0 Runs   6 Wickets  ' 
    },
  { name: "Mayank Agarwal",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/15.png",
    stats: '  11 Matches   424 Runs   0 Wickets  ' 
    },
  { name: "Mohammad Shami",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/16.png",
    stats: '  14 Matches   2 Runs   20 Wickets  ' 
    },
  { name: "Darshan Nalkande",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/17.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' 
    },
  { name: "Nicholas Pooran",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/18.png",
    stats: '  14 Matches   353 Runs   0 Wickets  ' 
    },
  { name: "Chris Gayle",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/19.png",
    stats: '  7 Matches   288 Runs   0 Wickets  ' 
    },
  { name: "Murugan Ashwin",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/20.png",
    stats: '  9 Matches   4 Runs   10 Wickets  ' 
    },
  { name: "Jagadeesha Suchith",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/21.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' 
    },
  { name: "Krishnappa Gowtham",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/22.png",
    stats: '  2 Matches   42 Runs   1 Wickets  ' 
    },
  { name: "Hardus Viljoen",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/23.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' 
    },
  { name: "Simran Singh",
  isCaptain: false,
  team: "kxip",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kxip/24.png",
    stats: '  2 Matches   15 Runs   0 Wickets  '
     },
        { 
            name: 'Eoin Morgan', 
            isCaptain: true,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/0.png",
            stats: '  14 Matches   418 Runs   0 Wickets  ' },
        { 
            name: 'Andre Russell', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/1.png",
            stats: '  10 Matches   117 Runs   6 Wickets  ' },
        { 
            name: 'Dinesh Karthik', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/2.png",
            stats: '  14 Matches   169 Runs   0 Wickets  ' },
        { 
            name: 'Kamlesh Nagarkoti', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/3.png",
            stats: '  10 Matches   22 Runs   5 Wickets  ' },
        { 
            name: 'Kuldeep Yadav', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/4.png",
            stats: '  5 Matches   13 Runs   1 Wickets  ' },
        { 
            name: 'Lockie Ferguson', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/5.png",
            stats: '  5 Matches   43 Runs   6 Wickets  ' },
        { 
            name: 'Nitish Rana', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/6.png",
            stats: '  14 Matches   352 Runs   0 Wickets  ' },
        { 
            name: 'Prasidh Krishna', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/7.png",
            stats: '  6 Matches   2 Runs   4 Wickets  ' },
        { 
            name: 'Rinku Singh', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/8.png",
            stats: '  1 Matches   11 Runs   0 Wickets  ' },
        { 
            name: 'Sandeep Warrier', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/9.png",
            stats: '  1 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Shivam Mavi', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/10.png",
            stats: '  8 Matches   10 Runs   9 Wickets  ' },
        { 
            name: 'Shubman Gill', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/11.png",
            stats: '  14 Matches   440 Runs   0 Wickets  ' },
        { 
            name: 'Siddhesh Lad', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/12.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Sunil Narine', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/13.png",
            stats: '  10 Matches   121 Runs   5 Wickets  ' },
        { 
            name: 'Pat Cummins', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/14.png",
            stats: '  14 Matches   146 Runs   12 Wickets  ' },
        { 
            name: 'Rahul Tripathi', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/15.png",
            stats: '  11 Matches   230 Runs   0 Wickets  ' },
        { 
            name: 'Varun Chakravarthy', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/16.png",
            stats: '  13 Matches   10 Runs   17 Wickets  ' },
        { 
            name: 'M Siddharth', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/17.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Chris Green', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/18.png",
            stats: '  1 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Tom Banton', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/19.png",
            stats: '  2 Matches   18 Runs   0 Wickets  ' },
        { 
            name: 'Nikhil Naik', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/20.png",
            stats: '  1 Matches   1 Runs   0 Wickets  ' },
        { 
            name: 'Ali Khan', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/21.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Tim Seifert', 
            isCaptain: false,
            team: "kkr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/kkr/22.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        {
            name: 'Rohit Sharma',   
            isCaptain: true,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/0.png",
            stats: '  12 Matches   332 Runs   0 Wickets  ' },
        { 
            name: 'Digvijay Deshmukh',
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/1.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Quinton de Kock',
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/2.png",
            stats: '  16 Matches   503 Runs   0 Wickets  ' },
        { 
            name: 'Aditya Tare',    
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/3.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        {
            name: 'Saurabh Tiwary', 
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/4.png",
            stats: '  7 Matches   103 Runs   0 Wickets  ' },
        { 
            name: 'Jasprit Bumrah', 
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/5.png",
            stats: '  15 Matches   5 Runs   27 Wickets  ' },
        { 
            name: 'Dhawal Kulkarni',
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/6.png",
            stats: '  1 Matches   3 Runs   0 Wickets  ' },
        { 
            name: 'James Pattinson', 
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/7.png",
            stats: '  10 Matches   15 Runs   11 Wickets  ' },
        { 
            name: 'Nathan Coulter-Nile' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/8.png",
            stats: '  7 Matches   25 Runs   5 Wickets  ' },
        { 
            name: 'Trent Boult' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/9.png",
            stats: '  15 Matches   0 Runs   25 Wickets  ' },
        { 
            name: 'Jayant Yadav' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/10.png",
            stats: '  2 Matches   0 Runs   1 Wickets  ' },
        { 
            name: 'Suryakumar Yadav' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/11.png",
            stats: '  16 Matches   480 Runs   0 Wickets  ' },
        { 
            name: 'Krunal Pandya' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/12.png",
            stats: '  16 Matches   109 Runs   6 Wickets  ' },
        { 
            name: 'Kieron Pollard' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/13.png",
            stats: '  16 Matches   268 Runs   4 Wickets  ' },
        { 
            name: 'Rahul Chahar' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/14.png",
            stats: '  15 Matches   2 Runs   15 Wickets  ' },
        { 
            name: 'Chris Lynn' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/15.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Hardik Pandya' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/16.png",
            stats: '  14 Matches   281 Runs   0 Wickets  ' },
        { 
            name: 'Sherfane Rutherford' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/17.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Anmolpreet Singh' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/18.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Mohsin Khan' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/19.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Mitchell McClenaghan' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/20.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Prince Balwant Rai Singh' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/21.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Anukul Roy' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/22.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Ishan Kishan' ,
            isCaptain: false,
            team: "mi",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/mi/23.png",
            stats: '  14 Matches   516 Runs   0 Wickets  ' },
        { 
            name: 'Steve Smith',
            isCaptain: true,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/0.png",
            stats: '  14 Matches   311 Runs   0 Wickets  ' },
        { 
            name: 'Ben Stokes',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/1.png",
            stats: '  8 Matches   285 Runs   2 Wickets  ' },
        { 
            name: 'Sanju Samson',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/2.png",
            stats: '  14 Matches   375 Runs   0 Wickets  ' },
        { 
            name: 'Andrew Tye',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/3.png",
            stats: '  1 Matches   6 Runs   1 Wickets  ' },
        { 
            name: 'Kartik Tyagi',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/4.png",
            stats: '  10 Matches   4 Runs   9 Wickets  ' },
        { 
            name: 'Ankit Rajpoot',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/5.png",
            stats: '  6 Matches   9 Runs   2 Wickets  ' },
        { 
            name: 'Shreyas Gopal',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/6.png",
            stats: '  14 Matches   37 Runs   10 Wickets  ' },
        { 
            name: 'Rahul Tewatia',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/7.png",
            stats: '  14 Matches   255 Runs   10 Wickets  ' },
        { 
            name: 'Jaydev Unadkat',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/8.png",
            stats: '  7 Matches   9 Runs   4 Wickets  ' },
        { 
            name: 'Mayank Markande',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/9.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Mahipal Lomror',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/10.png",
            stats: '  3 Matches   59 Runs   0 Wickets  ' },
        { 
            name: 'Oshane Thomas',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/11.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Riyan Parag',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/12.png",
            stats: '  12 Matches   86 Runs   0 Wickets  ' },
        { 
            name: 'Yashasvi Jaiswal',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/13.png",
            stats: '  3 Matches   40 Runs   0 Wickets  ' },
        { 
            name: 'Anuj Rawat',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/14.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Akash Singh',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/15.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Jofra Archer',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/16.png",
            stats: '  14 Matches   113 Runs   20 Wickets  ' },
        { 
            name: 'David Miller',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/17.png",
            stats: '  1 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Jos Buttler',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/18.png",
            stats: '  13 Matches   328 Runs   0 Wickets  ' },
        { 
            name: 'Manan Vohra',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/19.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Shashank Singh',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/20.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        { 
            name: 'Varun Aaron',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/21.png",
            stats: '  3 Matches   1 Runs   0 Wickets  ' },
        { 
            name: 'Tom Curran',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/22.png",
            stats: '  5 Matches   83 Runs   3 Wickets  ' },
        { 
            name: 'Robin Uthappa',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/23.png",
            stats: '  12 Matches   196 Runs   0 Wickets  ' },
        { 
            name: 'Anirudha Joshi',
            isCaptain: false,
            team: "rr",
            url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rr/24.png",
            stats: '  0 Matches   0 Runs   0 Wickets  ' },
        {
    name: 'Virat Kohli',   
    isCaptain: true,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/0.png",
    stats: '  15 Matches   466 Runs   0 Wickets  ' },
  { 
    name: 'Mohammed Siraj',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/1.png",
    stats: '  9 Matches   17 Runs   11 Wickets  ' },
  { 
    name: 'Chris Morris',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/2.png",
    stats: '  9 Matches   34 Runs   11 Wickets  ' },
  { 
    name: 'Josh Philippe',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/3.png",
    stats: '  5 Matches   78 Runs   0 Wickets  ' },
  { 
    name: 'Moeen Ali',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/4.png",
    stats: '  3 Matches   12 Runs   1 Wickets  ' },
  { 
    name: 'Aaron Finch',  
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/5.png",
    stats: '  12 Matches   268 Runs   0 Wickets  ' },
  { 
    name: 'AB de Villiers',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/6.png",
    stats: '  15 Matches   454 Runs   0 Wickets  ' },
  { 
    name: 'Shahbaz Ahmed',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/7.png",
    stats: '  2 Matches   1 Runs   2 Wickets  ' },
  { 
    name: 'Parthiv Patel',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/8.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' },
  { 
    name: 'Yuzvendra Chahal',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/9.png",
    stats: '  15 Matches   1 Runs   21 Wickets  ' },
  { 
    name: 'Navdeep Saini',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/10.png",
    stats: '  13 Matches   27 Runs   6 Wickets  ' },
  { 
    name: 'Isuru Udana',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/11.png",
    stats: '  10 Matches   15 Runs   8 Wickets  ' },
  { 
    name: 'Dale Steyn',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/12.png",
    stats: '  3 Matches   1 Runs   1 Wickets  ' },
  { 
    name: 'Pawan Negi',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/13.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' },
  { 
    name: 'Devdutt Padikkal',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/14.png",
    stats: '  15 Matches   473 Runs   0 Wickets  ' },
  { 
    name: 'Shivam Dube',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/15.png",
    stats: '  11 Matches   129 Runs   4 Wickets  ' },
  { 
    name: 'Umesh Yadav',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/16.png",
    stats: '  2 Matches   0 Runs   0 Wickets  ' },
  { 
    name: 'Gurkeerat Mann Singh',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/17.png",
    stats: '  8 Matches   71 Runs   0 Wickets  ' },
  { 
    name: 'Washington Sundar',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/18.png",
    stats: '  15 Matches   111 Runs   8 Wickets  ' },
  { 
    name: 'Pavan Deshpande',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/19.png",
    stats: '  0 Matches   0 Runs   0 Wickets  ' },
  { 
    name: 'Adam Zampa',   
    isCaptain: false,
    team: "rcb",
    url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/rcb/20.png",
    stats: '  3 Matches   0 Runs   2 Wickets  ' },

    {
        name: 'David Warner',
        isCaptain: true,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/0.png",
        stats: '  16 Matches   548 Runs   0 Wickets  ' },
    {
        name: 'Rashid Khan',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/1.png",
        stats: '  16 Matches   35 Runs   20 Wickets  ' },
    {
        name: 'Sanjay Yadav',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/2.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Wriddhiman Saha',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/3.png",
        stats: '  4 Matches   214 Runs   0 Wickets  ' },
    {
        name: 'Khaleel Ahmed',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/4.png",
        stats: '  7 Matches   0 Runs   8 Wickets  ' },
    {
        name: 'Sandeep Sharma',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/5.png",
        stats: '  13 Matches   12 Runs   14 Wickets  ' },
    {
        name: 'Abdul Samad',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/6.png",
        stats: '  12 Matches   111 Runs   1 Wickets  ' },
    {
        name: 'Mitchell Marsh',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/7.png",
        stats: '  1 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Shreevats Goswami',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/8.png",
        stats: '  2 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Mohammad Nabi',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/9.png",
        stats: '  1 Matches   11 Runs   0 Wickets  ' },
    {
        name: 'Fabian Allen',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/10.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Abhishek Sharma',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/11.png",
        stats: '  8 Matches   71 Runs   2 Wickets  ' },
    {
        name: 'Basil Thampi',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/12.png",
        stats: '  1 Matches   0 Runs   1 Wickets  ' },
    {
        name: 'Billy Stanlake',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/13.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Sandeep Bavanaka',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/14.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Jason Holder',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/15.png",
        stats: '  7 Matches   66 Runs   14 Wickets  ' },
    {
        name: 'Bhuvneshwar Kumar',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/16.png",
        stats: '  4 Matches   0 Runs   3 Wickets  ' },
    {
        name: 'Virat Singh',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/17.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'T Natarajan',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/18.png",
        stats: '  16 Matches   3 Runs   16 Wickets  ' },
    {
        name: 'Kane Williamson',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/19.png",
        stats: '  12 Matches   317 Runs   0 Wickets  ' },
    {
        name: 'Shahbaz Nadeem',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/20.png",
        stats: '  7 Matches   7 Runs   5 Wickets  ' },
    {
        name: 'Jonny Bairstow',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/21.png",
        stats: '  11 Matches   345 Runs   0 Wickets  ' },
    {
        name: 'Manish Pandey',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/22.png",
        stats: '  16 Matches   425 Runs   0 Wickets  ' },
    {
        name: 'Vijay Shankar',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/23.png",
        stats: '  7 Matches   97 Runs   4 Wickets  ' },
    {
        name: 'Siddarth Kaul',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/24.png",
        stats: '  1 Matches   0 Runs   2 Wickets  ' },
    {
        name: 'Prithvi Raj Yarra',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/25.png",
        stats: '  0 Matches   0 Runs   0 Wickets  ' },
    {
        name: 'Priyam Garg',
        isCaptain: false,
        team: "srh",
        url: "http://joshi24.myweb.cs.uwindsor.ca/static-img/srh/26.png",
        stats: '  14 Matches   133 Runs   0 Wickets  ' }
]

module.exports.players = players;
module.exports.teams = teams;
